name: Main Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag_pr_commit:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      NEW_TAG: ${{ steps.update_package_version.outputs.NEW_TAG }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY_ED25519 }}
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Get version type
        id: version_type
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          VERSION_TYPE=$(echo "$PR_TITLE" | cut -d "[" -f2 | cut -d "]" -f1)
          echo "VERSION_TYPE=$VERSION_TYPE" >> "$GITHUB_OUTPUT"
      - name: Update package version
        id: update_package_version
        run: |
          npm version ${{ steps.version_type.outputs.VERSION_TYPE }}
          echo "NEW_TAG=v$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
      - run: |
          git push origin HEAD
          git push origin ${{ steps.update_package_version.outputs.NEW_TAG }}

  build_and_release:
    needs: tag_pr_commit
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.tag_pr_commit.outputs.NEW_TAG }}
      - run: npm ci
      - run: npm run build
      - name: Make Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          path: ./build
          filename: release.zip
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.tag_pr_commit.outputs.NEW_TAG }}
          files: release.zip

  trigger_parent:
    needs: build_and_release
    runs-on: ubuntu-latest
    steps:
      - run: >
          curl -X POST
          -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}"
          -H "Accept: application/vnd.github.everest-preview+json"
          -H "Content-Type: application/json"
          --data '{"ref": "main"}'
          https://api.github.com/repos/benz2012/wiggle-tools/actions/workflows/main.yml/dispatches
